### ISSUE TITLE
Within openPatientTab Function, tab Returning with "+"

### ISSUE THREAD

**Issue by rknamba** [geekmdtravis/fluent-cerner-js#110]
When entering 'SBAR' for the tab and console logging the result, a + and ^^ are being appended. I also tried changing the tab name to 'Orders' and the same syntax was returned. Both attempts were case sensitive.
/FIRSTTAB=^SBAR+^

**Comment by rknamba** [comment]
While in PowerChart, when invoking an onClick function to execute the openPatientTab function, the expected result for inPowerChart should be true, however it is resulting as false.

**Comment by geekmdtravis** [comment]
Second issue is same as #112 and #111. the first is actually epected behavior.  Example from the Cerner docs:

`APPLINK(0,"$APP_APPNAME$","/PERSONID=589848 /ENCNTRID=5960967 /FIRSTTAB=^PowerOrders+^")`

**Comment by geekmdtravis** [comment]
@rknamba  - can you please test these functions again? simply updated to the pre-release version 1.0.0-2 and redeploy your app into PowerChart.

**Comment by rknamba** [comment]
Just tested this, and it appears to be working now.
