### ISSUE TITLE
inPowerChart Returning as False in openWebsiteByUrl Function

### ISSUE THREAD

**Issue by rknamba** [geekmdtravis/fluent-cerner-js#111]
Result 
{inPowerChart: false, eventString: '', badInput: false}

After invoking the onClick function to execute the openWebsiteByUrl function, inPowerChart returning as false and eventString coming back as an empty string.

**Comment by geekmdtravis** [comment]
Same as issue #112

**Comment by geekmdtravis** [comment]
@rknamba  - can you please test these functions again? simply updated to the pre-release version 1.0.0-2 and redeploy your app into PowerChart.

**Comment by rknamba** [comment]
Tested, working as expected.
