### ISSUE TITLE
inPowerChart Returning as False in openOrganizerTab Function

### ISSUE THREAD

**Issue by rknamba** [geekmdtravis/fluent-cerner-js#112]
Result
{inPowerChart: false, eventString: '/ORGANIZERTAB=^PROVIDER HUB^', badInput: false}

After invoking the onClick function to execute the openOrganizerTab function, inPowerChart returning as false. eventString is returning the org tab name in all caps, should this be returning as case sensitive?

**Comment by geekmdtravis** [comment]
Almost assuredly due to the fact that `APPLINK` is accessed as `window.external.APPLINK` in the current implementation. I believe we can access it either `APPLINK` directly or `window.APPLINK`.

**Comment by geekmdtravis** [comment]
@rknamba  - can you please test these functions again? simply updated to the pre-release version 1.0.0-2 and redeploy your app into PowerChart.

**Comment by rknamba** [comment]
Tested, working as expected.
